### ISSUE TITLE
스텔스 모드 토글 단축키 추가가 가능할까요?

### ISSUE THREAD

**Issue by Lucid0418** [green1052/DCRefresher-Reborn-Archive#221]
![image](https://user-images.githubusercontent.com/18731129/189786118-81c0b0e2-32c8-484e-9eb3-558e1a90d708.png)
![image](https://user-images.githubusercontent.com/18731129/189786154-a24946ac-037d-4a37-b7b8-4d1a5298d7a9.png)

공앱처럼 본문 내에서 이미지 보기를 빠르게 켰다 껐다 할 수 있으면 좋을 것 같습니다.
현재는 확장 프로그램 전체를 껐다 켜는 단축키를 사용하거나 상단의 확장 프로그램 아이콘을 일일이 클릭해서 기능을 토글하는 방법밖에 없어서 조금 손이 많이 가네요.

번거로우시겠지만 검토 부탁드립니다.

**Comment by green1052** [comment]
기능 추가 후 알려드리겠습니다.
